name: CD Workflow

on:
  push:
    branches:
      - main   # Trigger CD workflow on push to the main branch (after CI passes)

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures CD job runs only after CI job succeeds

    steps:
      # Checkout code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx (needed for building multi-platform images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # DockerHub username stored as a secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # DockerHub password stored as a secret

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t my_project:${{ github.sha }} .
          docker tag my_project:${{ github.sha }} username/my_project:latest  # Replace with your DockerHub username

      # Push Docker image to DockerHub
      - name: Push Docker image to DockerHub
        run: |
          docker push username/my_project:latest  # Replace with your DockerHub username

      # Optional: Deploy to remote server or cloud environment
      - name: Deploy to AWS EC2 (Example)
        run: |
          ssh -i ~/.ssh/your-key.pem ec2-user@your-ec2-public-ip 'docker pull username/my_project:latest && docker run -d --name my_project username/my_project:latest'